# version: "3.8"
# originaly version 3.8, but 3 for production, property version 2 is useless.

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile

        container_name: laravel_app
        ports:
            - "8080:8080" # Map Laravel server ke port 8080
        volumes:
            - .:/var/www/html
        networks:
            - app_network
        depends_on:
            - db

        command: >
            sh -c "
            npm install &&
            npm run dev &
            php artisan serve --host=0.0.0.0 --port=8080
            "

    db:
        image: mysql:8.0.0
        container_name: laravel_db
        restart: always
        ports:
            - "8306:3306"
        environment:
            MYSQL_DATABASE: maesa_camp
            MYSQL_ROOT_PASSWORD:
            MYSQL_USER: root
            MYSQL_PASSWORD:
        networks:
            - app_network
        volumes:
            - db_data:/var/lib/mysql

    node:
        image: node:18
        container_name: laravel_node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - app_network

        ## command: ["npm", "run", "dev"]
        command: npm install && npm run dev
networks:
    app_network:

volumes:
    db_data:
